ocamlyices2: misc.c: fixed compilation when no FDOPEN/FDCOOKIE available
src/misc.c:155:1: error: attributes should be specified before
the declarator in a function definition:
 static inline FILE *fopen_write_callback(UNUSED void *cookie,
 ^